# Anwendung der .query() Funktion in Python

Dieses Notebook soll verschiedene Anwendungen der .query() aufzeigen und dessen Bedeutung darstellen.

In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/EikeSuemper/Meine-Lernreise-Aktuariat-QuantFinance/refs/heads/main/04_Datens%C3%A4tze/sales_data.xls")
df

,OrderID,Date,CustomerID,Product,Category,Quantity,UnitPrice,Store,Region,Salesperson,Discount,TotalSales
0,1001,2023-02-21,316,Monitor,Accessories,6,997.09,Cologne,West,Ben,0.02,5862.8892
1,1002,2023-04-03,351,Laptop,Accessories,3,434.30,Cologne,West,Ben,0.04,1250.7840
2,1003,2023-01-15,287,Tablet,Electronics,6,1433.20,Munich,North,Ben,0.04,8255.2320
3,1004,2023-03-13,479,Mouse,Accessories,8,1112.09,Munich,North,Clara,0.21,7028.4088
4,1005,2023-03-02,140,Keyboard,Accessories,2,840.44,Munich,West,Clara,0.25,1260.6600
...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2023-03-26,484,Printer,Electronics,1,506.42,Frankfurt,West,David,0.28,364.6224
96,1097,2023-03-21,476,Mouse,Accessories,1,1015.33,Munich,South,Ben,0.22,791.9574
97,1098,2023-03-23,382,Headphones,Accessories,2,1133.51,Munich,West,David,0.01,2244.3498
98,1099,2023-02-22,220,Laptop,Accessories,6,1191.54,Frankfurt,East,Ben,0.23,5504.9148
99,1100,2023-01-24,215,Laptop,Accessories,9,1188.63,Munich,West,Emma,0.25,8023.2525

### Aufgabe 1

Finde alle Bestellungen mit einem Gesamtumsatz (TotalSales) größer als 5000€.

In [25]:
A = df.query("TotalSales >= 5000")
A[["OrderID","Product", "Quantity", "Date", "TotalSales"]].head()

    OrderID  Product  Quantity        Date  TotalSales
0      1001  Monitor         6  2023-02-21   5862.8892
2      1003   Tablet         6  2023-01-15   8255.2320
3      1004    Mouse         8  2023-03-13   7028.4088
15     1016    Mouse         6  2023-02-22   6177.4062
30     1031    Mouse         9  2023-04-01   6536.2959

### Aufgabe 2

Zeige alle Verkäufe in der Region 'North' oder 'South', bei denen die Menge (Quantity) mindestens 5 beträgt.

In [26]:
B = df.query("Quantity >= 5 and Region in ['North', 'South']")
B[["OrderID","Product", "Quantity", "Date", "TotalSales", "Region"]].head()

    OrderID   Product  Quantity        Date  TotalSales Region
2      1003    Tablet         6  2023-01-15   8255.2320  North
3      1004     Mouse         8  2023-03-13   7028.4088  North
14     1015   Printer         5  2023-01-22   4822.8000  North
17     1018  Keyboard         9  2023-03-29   1379.2923  North
18     1019   Printer         5  2023-01-30   3364.1550  North

### Aufgabe 3

Finde alle Verkäufe von Laptop oder Smartphone in Berlin oder Munich, bei denen der Rabatt (Discount) unter 10 % liegt und das Datum nach dem 1. März 2023 liegt.

In [32]:
df.query("Product in ['Laptop', 'Smartphone'] and Store in ['Berlin', 'Munich'] and Discount < 0.10 and Date > '2023-03-01'")

,OrderID,Date,CustomerID,Product,Category,Quantity,UnitPrice,Store,Region,Salesperson,Discount,TotalSales
10,1011,2023-03-29,426,Laptop,Accessories,4,41.3,Munich,North,Clara,0.03,160.244